 'use strict';
(()=>{
const root=document.getElementById('app'),C=window.BARBER_CONFIG;
let session=null,shop=null,services=[],staff=[],clients=[],appointments=[],current='home',selectedSlot='',capabilities=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const isoDay=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const slug=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55);
const shell=(body,nav='')=>{root.innerHTML=`<header><div class="brand">✂ <span class="gold">Barber</span>Agenda <span class="small">V2</span></div><span class="pill">Nova versão</span></header><main class="wrap">${nav}${body}</main><footer>BarberAgenda • Seu negócio, sua agenda</footer>`};
const msg=(s,ok=false)=>{const el=document.getElementById('msg');if(el){el.textContent=s;el.className='alert'+(ok?' ok':'')}};
const error=e=>msg(e?.message||String(e));
async function req(path,{method='GET',body,auth=false,headers={}}={}){if(!C?.supabaseUrl||!C?.publishableKey)throw Error('Configuração Supabase ausente');const h={'apikey':C.publishableKey,...headers};if(body!==undefined)h['Content-Type']='application/json';if(auth){if(!session?.access_token)throw Error('Faça login novamente');h.Authorization='Bearer '+session.access_token}const r=await fetch(C.supabaseUrl+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});let d;try{d=await r.json()}catch{d=null}if(!r.ok)throw Error(d?.message||d?.error_description||d?.msg||d?.error||`Erro ${r.status}`);return d}
const table=(t,query='',opts={})=>req('/rest/v1/'+t+(query?'?'+query:''),opts);
const saveSession=s=>{session=s;try{s?localStorage.setItem('ba_v2_session',JSON.stringify(s)):localStorage.removeItem('ba_v2_session')}catch{}};
const nav=()=>`<div class="nav">${[['dashboard','Painel'],['services','Serviços'],['staff','Profissionais'],['appointments','Agenda'],['clients','Clientes'],['settings','Configurações']].map(([k,v])=>`<button class="${current===k?'active':''}" onclick="BA.go('${k}')">${v}</button>`).join('')}<button onclick="BA.logout()">Sair</button></div>`;
const field=(name,label,type='text',val='',extra='')=>`<label>${label}</label><input name="${name}" type="${type}" value="${esc(val)}" ${extra}>`;
function home(){current='home';shell(`<section class="hero"><span class="pill">Gestão inteligente de barbearias</span><h1>Sua barbearia organizada, <span class="gold">seu tempo valorizado.</span></h1><p class="muted">Agendamentos, profissionais, fidelidade e controle de atendimentos em um só lugar.</p></section><div class="card"><h2>Bem-vindo</h2><p class="muted">Entre ou cadastre sua barbearia para começar.</p><button class="btn" onclick="BA.login()">Entrar</button><button class="btn secondary" onclick="BA.signup()">Criar conta</button></div>`)}
function login(){shell(`<h1>Entrar</h1><form id="form" class="card">${field('email','E-mail','email','','required autocomplete="email"')}${field('password','Senha','password','','required')}<button class="btn">Entrar</button><div id="msg"></div></form><button class="link" onclick="BA.signup()">Criar conta</button>`);document.getElementById('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const f=new FormData(e.target),d=await req('/auth/v1/token?grant_type=password',{method:'POST',body:{email:f.get('email'),password:f.get('password')}});saveSession(d);await loadShop()}catch(ex){error(ex)}finally{b.disabled=false}}}
function signup(){shell(`<h1>Criar conta</h1><p class="muted">Comece pelo acesso do responsável.</p><form id="form" class="card">${field('email','E-mail','email','','required')}${field('password','Senha (mínimo 8 caracteres)','password','','required minlength="8"')}<button class="btn">Cadastrar</button><div id="msg"></div></form><button class="link" onclick="BA.login()">Já tenho conta</button>`);document.getElementById('form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),d=await req('/auth/v1/signup',{method:'POST',body:{email:f.get('email'),password:f.get('password')}});if(d?.access_token){saveSession(d);await loadShop()}else msg('Cadastro enviado. Confirme seu e-mail se a confirmação estiver habilitada no Supabase.',true)}catch(ex){error(ex)}}}
async function loadShop(){try{const u=await req('/auth/v1/user',{auth:true});const rows=await table('ba2_barbearias','select=*&owner_id=eq.'+encodeURIComponent(u.id)+'&limit=1',{auth:true});shop=rows[0]||null;if(!shop)return setupShop();await refresh();go('dashboard')}catch(ex){saveSession(null);shell(`<h2>Não foi possível abrir a conta</h2><div class="alert">${esc(ex.message)}</div><button class="btn" onclick="BA.login()">Voltar ao login</button>`)}}
function setupShop(){shell(`<h1>Cadastre sua barbearia</h1><p class="muted">Seu teste grátis começa quando criar a barbearia.</p><form id="form" class="card">${field('nome','Nome da barbearia','text','','required')}${field('responsavel','Nome do responsável','text','','required')}${field('whatsapp','WhatsApp com DDD','tel','','required')}<button class="btn">Criar barbearia</button><div id="msg"></div></form>`);document.getElementById('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const f=new FormData(e.target),u=await req('/auth/v1/user',{auth:true}),nome=f.get('nome');const payload={owner_id:u.id,nome,responsavel:f.get('responsavel'),whatsapp:f.get('whatsapp'),slug:slug(nome)+'-'+u.id.slice(0,6)};const r=await table('ba2_barbearias','select=*',{method:'POST',body:payload,auth:true,headers:{Prefer:'return=representation'}});shop=r[0];await refresh();go('dashboard')}catch(ex){error(ex)}finally{b.disabled=false}}}
async function refresh(){if(!shop)return;const q='shop_id=eq.'+shop.id+'&select=*';[services,staff,clients,appointments]=await Promise.all(['ba2_servicos','ba2_profissionais','ba2_clientes','ba2_agendamentos'].map(t=>table(t,q,{auth:true})));capabilities=await table('ba2_staff_services',q,{auth:true})}
const link=()=>{const u=new URL(window.location.href);u.search='';u.hash='';u.searchParams.set('barbearia',shop.slug);return u.href};
function go(page){current=page;if(!shop)return home();if(page==='dashboard'){const until=new Date(shop.trial_ends_at),expired=until.getTime()<Date.now();shell(`<h1>Olá, ${esc(shop.nome)} ✂</h1><p class="muted">Gerencie sua barbearia em um só lugar.</p><div class="grid"><div class="card"><div class="muted">Profissionais</div><div class="stat">${staff.length}</div></div><div class="card"><div class="muted">Serviços</div><div class="stat">${services.length}</div></div><div class="card"><div class="muted">Agendamentos</div><div class="stat">${appointments.length}</div></div><div class="card"><div class="muted">Clientes</div><div class="stat">${clients.length}</div></div></div><div class="card"><h2>${expired?'Teste encerrado':'Teste grátis ativo'}</h2><p>Até ${until.toLocaleDateString('pt-BR')}</p><p class="hint">O controle de assinatura e cobrança deverá ser ativado antes da venda comercial.</p></div><div class="card"><h2>Seu link público</h2><p><a href="${esc(link())}">${esc(link())}</a></p><button class="btn" onclick="BA.copyLink()">Copiar link</button><p class="hint">Para clientes externos, publique os arquivos em hospedagem HTTPS antes de divulgar.</p></div>`,nav());return}
if(page==='services'||page==='staff'){const isS=page==='services',arr=isS?services:staff;const name=isS?'Serviços':'Profissionais';shell(`<h1>${name}</h1><form class="card" id="form"><h2>Adicionar ${isS?'serviço':'profissional'}</h2>${field('nome','Nome','text','','required')}${isS?field('preco','Preço em reais','number','','required min="0" step="0.01"')+field('duracao','Duração em minutos','number','30','required min="5" max="600"'):field('whatsapp','WhatsApp (opcional)','tel')}<button class="btn">Salvar</button><div id="msg"></div></form><div class="card"><h2>Cadastrados (${arr.length})</h2>${arr.length?arr.map(x=>`<div class="item row"><div><strong>${esc(x.nome)}</strong><br><small>${isS?money(x.preco)+' • '+x.duracao+' min':esc(x.whatsapp||'Sem WhatsApp')}</small></div>${!isS?`<button class="link" onclick="BA.capability('${x.id}')">Serviços que faz</button>`:''}<button class="link" onclick="BA.remove('${page}','${x.id}')">Excluir</button></div>`).join(''):'<p class="muted">Nenhum cadastro ainda.</p>'}</div>`,nav());document.getElementById('form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),body={shop_id:shop.id,nome:f.get('nome')};if(isS){body.preco=Number(f.get('preco'));body.duracao=Number(f.get('duracao'))}else body.whatsapp=f.get('whatsapp');await table(isS?'ba2_servicos':'ba2_profissionais','',{method:'POST',body,auth:true});await refresh();go(page)}catch(ex){error(ex)}};return}
if(page==='appointments'){shell(`<h1>Agenda</h1><p class="muted">Agendamentos realizados pelo link público.</p><div class="card">${appointments.length?appointments.slice().sort((a,b)=>a.inicio.localeCompare(b.inicio)).map(a=>`<div class="item"><strong>${new Date(a.inicio).toLocaleString('pt-BR')}</strong> • ${esc(a.cliente_nome)}<br><small>${esc(services.find(x=>x.id===a.servico_id)?.nome||'Serviço')} • ${esc(staff.find(x=>x.id===a.profissional_id)?.nome||'Profissional')} • ${esc(a.status)}</small><div class="inline">${a.status==='marcado'?`<button class="link" onclick="BA.status('${a.id}','concluido')">Concluir</button><button class="link" onclick="BA.status('${a.id}','cancelado')">Cancelar</button>`:''}</div></div>`).join(''):'<p class="muted">Nenhum agendamento.</p>'}</div>`,nav());return}
if(page==='clients'){shell(`<h1>Clientes e fidelidade</h1><p class="muted">1 ponto por atendimento concluído, conforme configuração inicial.</p><div class="card">${clients.length?clients.map(c=>`<div class="item row"><div><strong>${esc(c.nome)}</strong><br><small>${esc(c.whatsapp)} • ${c.pontos||0} pontos</small></div></div>`).join(''):'<p class="muted">Os clientes aparecerão após o primeiro agendamento.</p>'}</div>`,nav());return}
if(page==='settings'){shell(`<h1>Configurações</h1><div class="card"><p><strong>Barbearia:</strong> ${esc(shop.nome)}</p><p><strong>Identificador:</strong> ${esc(shop.slug)}</p><p><strong>Link:</strong> <a href="${esc(link())}">${esc(link())}</a></p><p class="hint">Horários padrão: 09:00 às 18:00, de segunda a sábado. A configuração avançada de expediente será adicionada em pacote posterior.</p></div>`,nav())}}
async function remove(page,id){if(!confirm('Excluir este cadastro?'))return;try{await table(page==='services'?'ba2_servicos':'ba2_profissionais','id=eq.'+id,{method:'DELETE',auth:true});await refresh();go(page)}catch(ex){alert(ex.message)}}
async function status(id,s){try{await table('ba2_agendamentos','id=eq.'+id,{method:'PATCH',body:{status:s},auth:true});await refresh();go('appointments')}catch(ex){alert(ex.message)}}
function copyLink(){if(navigator.clipboard?.writeText){navigator.clipboard.writeText(link()).then(()=>alert('Link copiado!')).catch(()=>prompt('Copie o link:',link()))}else prompt('Copie o link:',link())}
function capability(id){const p=staff.find(x=>x.id===id);if(!p)return;const existing=capabilities.filter(x=>x.profissional_id===id).map(x=>x.servico_id);shell(`<h1>Serviços de ${esc(p.nome)}</h1><p class="muted">Marque os serviços que este profissional realiza. Se nenhum for marcado, ele poderá realizar todos (padrão).</p><form id="caps" class="card">${services.map(s=>`<label class="checkrow"><input type="checkbox" name="service" value="${s.id}" ${existing.includes(s.id)?'checked':''}> ${esc(s.nome)}</label>`).join('')}<button class="btn">Salvar especialidades</button><div id="msg"></div></form><button class="link" onclick="BA.go('staff')">Voltar</button>`,nav());document.getElementById('caps').onsubmit=async e=>{e.preventDefault();const selected=[...e.target.querySelectorAll('input:checked')].map(x=>x.value);try{await table('ba2_staff_services','profissional_id=eq.'+id,{method:'DELETE',auth:true});for(const servico_id of selected)await table('ba2_staff_services','',{method:'POST',auth:true,body:{shop_id:shop.id,profissional_id:id,servico_id}});await refresh();go('staff')}catch(ex){error(ex)}}}
async function publicPage(sl){shell('<h1>Agendamento online</h1><p class="muted">Carregando horários...</p>');try{
 const result=await req('/rest/v1/rpc/ba2_public_shop',{method:'POST',body:{p_slug:sl}});const r=Array.isArray(result)?result[0]:result;if(!r?.id)throw Error('Barbearia não encontrada');shop=r;
 const [s,p,caps]=await Promise.all([
 req('/rest/v1/rpc/ba2_public_services',{method:'POST',body:{p_shop_id:r.id}}),
 req('/rest/v1/rpc/ba2_public_staff',{method:'POST',body:{p_shop_id:r.id}}),
 req('/rest/v1/rpc/ba2_public_capabilities',{method:'POST',body:{p_shop_id:r.id}})]);
 services=s;staff=p;capabilities=caps;
 shell(`<h1>✂ ${esc(r.nome)}</h1><p class="muted">Escolha quantos serviços quiser. Se necessário, selecione profissionais diferentes.</p><form id="booking" class="card"><h2>1. Escolha os serviços</h2><div id="choices">${s.map(x=>`<label class="checkrow"><input type="checkbox" name="services" value="${x.id}"> <span>${esc(x.nome)} — ${money(x.preco)} • ${x.duracao} min</span></label>`).join('')}</div><div id="assignments"></div><div id="total"></div><h2>2. Data e horário</h2>${field('dia','Data','date',isoDay(),`required min="${isoDay()}"`)}<div id="slots"></div><h2>3. Seus dados</h2>${field('nome','Seu nome','text','','required minlength="2"')}${field('whatsapp','WhatsApp com DDD','tel','','required minlength="8"')}<button class="btn" type="submit">Confirmar todos os serviços</button><div id="msg"></div></form>`);
 const form=document.getElementById('booking');let currentItems=[];let seq=0;
 const can=(pid,sid)=>{const set=caps.filter(x=>x.profissional_id===pid);return !set.length||set.some(x=>x.servico_id===sid)};
 const getItems=()=>[...document.querySelectorAll('#assignments select')].map(x=>({servico_id:x.dataset.service,profissional_id:x.value}));
 const update=async()=>{const run=++seq;selectedSlot='';const el=document.getElementById('slots'),day=form.elements.dia.value;currentItems=getItems();if(!currentItems.length||currentItems.some(x=>!x.profissional_id)||!day){el.innerHTML='<p class="hint">Escolha os serviços, profissionais e a data.</p>';return}el.innerHTML='<p class="hint">Buscando horários para todos os serviços...</p>';try{const slots=await req('/rest/v1/rpc/ba2_multi_slots',{method:'POST',body:{p_shop_id:r.id,p_items:currentItems,p_day:day}});if(run!==seq)return;el.innerHTML=`<label>Horários de início disponíveis</label><div class="slots">${slots.length?slots.map(x=>`<button type="button" data-time="${esc(x.hora)}">${esc(x.hora)}</button>`).join(''):'Nenhum horário disponível nessa data.'}</div>`;el.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedSlot=b.dataset.time;el.querySelectorAll('button').forEach(v=>v.classList.remove('selected'));b.classList.add('selected')})}catch(ex){if(run===seq)el.innerHTML='<div class="alert">'+esc(ex.message)+'</div>'}};
 const render=()=>{const chosen=[...form.querySelectorAll('input[name="services"]:checked')].map(x=>s.find(v=>v.id===x.value));const old={};document.querySelectorAll('#assignments select').forEach(x=>old[x.dataset.service]=x.value);const same=staff.find(p=>chosen.every(s=>can(p.id,s.id)));const preferred=same?.id||'';
 document.getElementById('assignments').innerHTML=chosen.length?`<h2>Profissionais por serviço</h2>${chosen.map(s=>{const available=staff.filter(p=>can(p.id,s.id));const preferredId=available.some(p=>p.id===old[s.id])?old[s.id]:(available.some(p=>p.id===preferred)?preferred:available[0]?.id||'');return `<label>${esc(s.nome)}</label><select data-service="${s.id}" required><option value="">Escolha</option>${available.map(p=>`<option value="${p.id}" ${p.id===preferredId?'selected':''}>${esc(p.nome)}</option>`).join('')}</select>${available.length?'':'<p class="alert">Nenhum profissional habilitado para este serviço.</p>'}`}).join('')}`:'<p class="hint">Selecione pelo menos um serviço.</p>';
 document.getElementById('total').innerHTML=chosen.length?`<div class="card"><strong>Total: ${money(chosen.reduce((v,x)=>v+Number(x.preco),0))}</strong><p class="hint">Duração total: ${chosen.reduce((v,x)=>v+x.duracao,0)} minutos • Atendimentos em sequência</p></div>`:'';
 document.querySelectorAll('#assignments select').forEach(x=>x.onchange=update);update()};
 form.querySelectorAll('input[name="services"]').forEach(x=>x.onchange=render);form.elements.dia.onchange=update;render();
 form.onsubmit=async e=>{e.preventDefault();if(!selectedSlot){msg('Escolha um horário disponível.');return}const items=getItems(),f=new FormData(form),btn=form.querySelector('button[type="submit"]'),time=selectedSlot;btn.disabled=true;try{const group=await req('/rest/v1/rpc/ba2_multi_book',{method:'POST',body:{p_shop_id:r.id,p_items:items,p_day:f.get('dia'),p_time:time,p_name:f.get('nome'),p_whatsapp:f.get('whatsapp')}});if(!group)throw Error('Não foi possível confirmar');shell(`<div class="card"><h1>Agendamento confirmado! ✅</h1><p>${esc(f.get('nome'))}, seus ${items.length} serviço(s) foram reservados para ${esc(f.get('dia'))}, começando às ${esc(time)}.</p><p class="muted">Os serviços serão realizados em sequência. Entre em contato com a barbearia se precisar cancelar.</p><button class="btn" onclick="location.reload()">Novo agendamento</button></div>`)}catch(ex){error(ex);await update()}finally{btn.disabled=false}}
 }catch(ex){shell(`<div class="alert">${esc(ex.message)}</div><p class="hint">Confira se o SQL atualizado foi instalado.</p>`)}}

async function start(){try{const params=new URLSearchParams(location.search);if(params.has('barbearia'))return publicPage(params.get('barbearia'));try{session=JSON.parse(localStorage.getItem('ba_v2_session')||'null')}catch{}if(session?.access_token)return loadShop();home()}catch(ex){shell(`<div class="alert">Erro ao iniciar: ${esc(ex.message)}</div>`)}}
window.BA={login,signup,capability,logout(){saveSession(null);shop=null;home()},go,remove,status,copyLink};start();
})();